# Generated by Django 4.2.8 on 2025-06-15 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_update_sale_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={},
        ),
    ]
