# Generated by Django 4.2.8 on 2025-06-15 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_supplier_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockadjustment',
            options={'ordering': ['-date'], 'verbose_name': 'Stock Adjustment', 'verbose_name_plural': 'Stock Adjustments'},
        ),
        migrations.RenameField(
            model_name='stockadjustment',
            old_name='created_by',
            new_name='adjusted_by',
        ),
        migrations.RemoveField(
            model_name='stockadjustment',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='stockadjustment',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='stockadjustment',
            name='type',
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='adjustment_type',
            field=models.CharField(choices=[('count', 'Stock Count'), ('damage', 'Damage'), ('return', 'Return'), ('other', 'Other')], default='count', max_length=10),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='quantity_change',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='reason',
            field=models.TextField(default=''),
        ),
    ]
