# Generated by Django 4.2.8 on 2025-06-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_alter_stockadjustment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='expected_delivery',
            field=models.DateField(blank=True, null=True),
        ),
    ]
