# Generated by Django 4.2.8 on 2025-06-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0007_purchase_expected_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='stock_updated',
            field=models.BooleanField(default=False),
        ),
    ]
