# Generated by Django 4.2.8 on 2025-06-15 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0009_product_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseitem',
            options={},
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_quantity',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='received_quantity',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='user_permissions',
        ),
    ]
