# Generated by Django 4.2.8 on 2025-06-16 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0010_alter_purchaseitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockadjustment',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='reference_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
